# TradeMate Performance Configuration
# Tier-specific performance optimization settings
apiVersion: v1
kind: ConfigMap
metadata:
  name: performance-config
  namespace: gridworks
data:
  # Application performance settings
  app-config.yaml: |
    performance:
      shared_tier:
        api:
          timeout: 100  # 100ms SLA target
          max_connections: 100
          pool_size: 20
          keep_alive: 30
        cache:
          ttl: 300  # 5 minutes
          max_size: "2GB"
          eviction_policy: "lru"
        database:
          query_timeout: 50  # 50ms
          connection_pool: 25
          statement_cache: 100
          
      premium_tier:
        api:
          timeout: 50   # 50ms SLA target
          max_connections: 200
          pool_size: 50
          keep_alive: 15
        cache:
          ttl: 60   # 1 minute
          max_size: "8GB"
          eviction_policy: "lfu"
        database:
          query_timeout: 20  # 20ms
          connection_pool: 50
          statement_cache: 500

  # JVM optimization settings
  jvm-config.properties: |
    # Shared tier JVM settings
    shared.jvm.heap.min=2g
    shared.jvm.heap.max=4g
    shared.jvm.gc.collector=G1GC
    shared.jvm.gc.threads=4
    
    # Premium tier JVM settings (more aggressive)
    premium.jvm.heap.min=8g
    premium.jvm.heap.max=16g
    premium.jvm.gc.collector=ZGC
    premium.jvm.gc.threads=8
    premium.jvm.gc.parallel=true

  # Nginx performance tuning
  nginx.conf: |
    # Shared tier nginx configuration
    upstream shared_backend {
        least_conn;
        server shared-app-1:8080 max_fails=3 fail_timeout=30s;
        server shared-app-2:8080 max_fails=3 fail_timeout=30s;
        server shared-app-3:8080 max_fails=3 fail_timeout=30s;
        keepalive 32;
    }
    
    # Premium tier nginx configuration
    upstream premium_backend {
        least_conn;
        server premium-app-1:8080 max_fails=2 fail_timeout=10s;
        server premium-app-2:8080 max_fails=2 fail_timeout=10s;
        server premium-app-3:8080 max_fails=2 fail_timeout=10s;
        server premium-app-4:8080 max_fails=2 fail_timeout=10s;
        server premium-app-5:8080 max_fails=2 fail_timeout=10s;
        keepalive 64;
    }
    
    server {
        listen 80;
        server_name api.gridworks.ai;
        
        # Performance optimizations
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        client_max_body_size 10M;
        
        # Gzip compression
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_types text/plain application/json application/javascript text/css;
        
        # Caching headers
        location /api/v1/static/ {
            expires 1d;
            add_header Cache-Control "public, immutable";
        }
        
        # Shared tier routing
        location /api/v1/ {
            proxy_pass http://shared_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_connect_timeout 30s;
            proxy_send_timeout 90s;
            proxy_read_timeout 90s;
        }
    }
    
    server {
        listen 80;
        server_name premium.gridworks.ai;
        
        # Premium tier optimizations
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 30;  # Shorter for premium
        client_max_body_size 50M;
        
        # Premium tier routing
        location /api/v1/ {
            proxy_pass http://premium_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_connect_timeout 10s;  # Faster timeouts
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
            
            # Priority routing
            proxy_buffering off;
            proxy_request_buffering off;
        }
    }
---
# Performance testing job
apiVersion: batch/v1
kind: Job
metadata:
  name: performance-validation
  namespace: gridworks
spec:
  template:
    spec:
      containers:
      - name: load-tester
        image: gridworks/load-tester:latest
        env:
        - name: SHARED_API_URL
          value: "https://api.gridworks.ai"
        - name: PREMIUM_API_URL
          value: "https://premium.gridworks.ai"
        - name: TEST_DURATION
          value: "300"  # 5 minutes
        - name: SHARED_TARGET_RPS
          value: "1000"
        - name: PREMIUM_TARGET_RPS
          value: "500"
        command:
        - python3
        - /app/load-testing.py
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"
      restartPolicy: Never
  backoffLimit: 3