# ArgoCD Application for Shared Tier (LITE + PRO)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gridworks-shared-production
  namespace: argocd
  labels:
    tier: shared
    app.kubernetes.io/name: gridworks-shared
spec:
  project: gridworks-production
  
  source:
    repoURL: https://github.com/raosunjoy/TradeMate
    targetRevision: master
    path: infrastructure/k8s/shared-tier
    helm:
      valueFiles:
        - values-production.yaml
      parameters:
        - name: image.repository
          value: ghcr.io/raosunjoy/gridworks/shared-api
        - name: image.tag
          value: latest
        - name: replicaCount
          value: "10"
        - name: autoscaling.enabled
          value: "true"
        - name: autoscaling.minReplicas
          value: "5"
        - name: autoscaling.maxReplicas
          value: "50"
        - name: resources.requests.cpu
          value: "500m"
        - name: resources.requests.memory
          value: "512Mi"
        - name: resources.limits.cpu
          value: "1000m"
        - name: resources.limits.memory
          value: "1Gi"
        - name: service.type
          value: "ClusterIP"
        - name: ingress.enabled
          value: "true"
        - name: ingress.className
          value: "nginx"
        - name: ingress.hosts[0].host
          value: "api.gridworks.ai"
        - name: ingress.hosts[0].paths[0].path
          value: "/"
        - name: ingress.hosts[0].paths[0].pathType
          value: "Prefix"
        - name: env.TIER_MODE
          value: "SHARED"
        - name: env.PERFORMANCE_TARGET
          value: "100ms"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: shared
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 3
  
  # Health checks for shared tier
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/minReplicas
        - /spec/maxReplicas
  
  # Notification configuration
  operation:
    sync:
      syncStrategy:
        hook:
          force: true
      retry:
        limit: 5
        backoff:
          duration: 5s
          maxDuration: 3m
          factor: 2
